# Generated by Django 5.2.4 on 2025-07-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_title', models.CharField(max_length=255)),
                ('notification_description', models.TextField()),
                ('notification_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=9)),
                ('job_title', models.CharField(blank=True, max_length=50, null=True)),
                ('supervisor', models.CharField(blank=True, max_length=30, null=True)),
                ('department', models.CharField(blank=True, max_length=20, null=True)),
                ('jobDuties', models.TextField(blank=True, null=True)),
                ('performanceSummary', models.TextField(blank=True, null=True)),
                ('planning_comments', models.TextField(blank=True, null=True)),
                ('planning_employee_rating', models.IntegerField(blank=True, null=True)),
                ('planning_manager_rating', models.IntegerField(blank=True, null=True)),
                ('productivity_comments', models.TextField(blank=True, null=True)),
                ('productivity_employee_rating', models.IntegerField(blank=True, null=True)),
                ('productivity_manager_rating', models.IntegerField(blank=True, null=True)),
                ('quality_comments', models.TextField(blank=True, null=True)),
                ('quality_employee_rating', models.IntegerField(blank=True, null=True)),
                ('quality_manager_rating', models.IntegerField(blank=True, null=True)),
                ('knowledge_comments', models.TextField(blank=True, null=True)),
                ('knowledge_employee_rating', models.IntegerField(blank=True, null=True)),
                ('knowledge_manager_rating', models.IntegerField(blank=True, null=True)),
                ('innovation_comments', models.TextField(blank=True, null=True)),
                ('innovation_employee_rating', models.IntegerField(blank=True, null=True)),
                ('innovation_manager_rating', models.IntegerField(blank=True, null=True)),
                ('peerComm_comments', models.TextField(blank=True, null=True)),
                ('peerComm_employee_rating', models.IntegerField(blank=True, null=True)),
                ('peerComm_manager_rating', models.IntegerField(blank=True, null=True)),
                ('teamRel_comments', models.TextField(blank=True, null=True)),
                ('teamRel_employee_rating', models.IntegerField(blank=True, null=True)),
                ('teamRel_manager_rating', models.IntegerField(blank=True, null=True)),
                ('writing_comments', models.TextField(blank=True, null=True)),
                ('writing_employee_rating', models.IntegerField(blank=True, null=True)),
                ('writing_manager_rating', models.IntegerField(blank=True, null=True)),
                ('oralComm_comments', models.TextField(blank=True, null=True)),
                ('oralComm_employee_rating', models.IntegerField(blank=True, null=True)),
                ('oralComm_manager_rating', models.IntegerField(blank=True, null=True)),
                ('selfImprovement_comments', models.TextField(blank=True, null=True)),
                ('selfImprovement_employee_rating', models.IntegerField(blank=True, null=True)),
                ('selfImprovement_manager_rating', models.IntegerField(blank=True, null=True)),
                ('otherCriteria', models.TextField(blank=True, null=True)),
                ('futureGoals', models.TextField(blank=True, null=True)),
                ('overallSummary', models.TextField(blank=True, null=True)),
                ('employeeComments', models.TextField(blank=True, null=True)),
                ('managerComments', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
