# Generated by Django 5.2.4 on 2025-07-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancereview',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
