# Generated by Django 5.2.4 on 2025-07-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_review', '0002_alter_performancereview_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancereview',
            name='employee_id',
            field=models.CharField(default='UNKNOWN', max_length=20),
            preserve_default=False,
        ),
    ]
