# Generated by Django 5.2 on 2025-07-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_review', '0003_alter_performancereview_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('user_role', models.CharField(max_length=20)),
                ('reporting_manager', models.EmailField(max_length=254)),
            ],
        ),
    ]
