# Generated by Django 5.2 on 2025-07-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_review', '0004_userlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
