# Generated by Django 5.2 on 2025-07-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_review', '0005_managerlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerlist',
            name='manager_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
