# Generated by Django 5.2 on 2025-07-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_review', '0006_managerlist_manager_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
