# Generated by Django 5.2 on 2025-07-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_review', '0007_statuscheck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuscheck',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
