# Generated by Django 5.2 on 2025-07-21 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_designation_user_name_user_reporting_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='employee_name',
        ),
    ]
